### ISSUE TITLE
HMM error while trying to replicate the paper analysis 

### ISSUE THREAD

**Issue by Militeee** [negar7918/CopyMix#1]
Hi, 
When running the code with the last version of hmmlearn I get the following error. Could you, please, give me the library version that you used in the original analysis (or a hint to solve the problem)
![CopyMixIssue](https://user-images.githubusercontent.com/30956006/75806533-1fdf1000-5d84-11ea-9c78-ce26e5621262.png)

**Comment by negar7918** [comment]
Use python 3.6.2 and hmmlearn 0.2.1 and let me know if it solves the problem.

**Comment by negar7918** [comment]
Did you get it running?

**Comment by Militeee** [comment]
Yes, it works fine with hmmlearn 0.2.1
